# Generated by Django 6.0.2 on 2026-04-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='faculty',
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
